### Arrays
A single or multidimensional structure containing data of the same type(strings ,characters or the integers)

In [4]:
movie_vector <- c("akira","tyo","asdf","dfsf","weff","adasf","fedsf","afsd")
movie_array <- array(movie_vector,dim =c(5,3))
movie_array 

[,1]  [,2]  [,3] 
[1,] akira adasf asdf 
[2,] tyo   fedsf dfsf 
[3,] asdf  afsd  weff 
[4,] dfsf  akira adasf
[5,] weff  tyo   fedsf

## Accessing an array

In [5]:
movie_array[1, 3] # access by row and columns


[1] "asdf"

In [7]:
movie_array[1,] # Read the whole 1st row

[1] "akira" "adasf" "asdf"

In [10]:
movie_array[,3]# Read the whole 3rd row

[1] "asdf"  "dfsf"  "weff"  "adasf" "fedsf"

## MATRICES

In [12]:
movie_vector <- c("akira","tyo","asdf","dfsf","weff","adasf","fedsf","afsd")

movie_matrix <- matrix(movie_vector, nrow = 4,ncol = 2)

movie_matrix

[,1]  [,2] 
[1,] akira weff 
[2,] tyo   adasf
[3,] asdf  fedsf
[4,] dfsf  afsd

In [14]:
## change the order of display in terms of rows
movie_matrix <- matrix(movie_vector, nrow = 4,ncol = 2,byrow= TRUE)

movie_matrix

[,1]  [,2] 
[1,] akira tyo  
[2,] asdf  dfsf 
[3,] weff  adasf
[4,] fedsf afsd

## access the matrix

In [16]:
movie_matrix[2:3,1:2] # first defines range of rows then second range of col

[,1] [,2] 
[1,] asdf dfsf 
[2,] weff adasf